"""
PDF renderer — generates branded PDF reports from
``VulnerabilityReport`` objects.

Pipeline:
  1. Render Jinja2 HTML template with report data + branding
  2. Convert HTML → PDF via weasyprint (if available)
  3. Fall back to raw HTML bytes when weasyprint is unavailable

Branding config (dict):
  - ``company_name``: str — displayed in header
  - ``logo_url``: str — logo image URL
  - ``analyst``: str — analyst name
  - ``footer``: str — page footer text
  - ``primary_color``: str — CSS color (not yet wired to CSS vars)
"""
import logging
from pathlib import Path
from typing import Optional

from jinja2 import Environment, FileSystemLoader

from models.report_schemas import VulnerabilityReport

logger = logging.getLogger(__name__)

_TEMPLATES_DIR = Path(__file__).parent.parent / "templates"

# Lazy-loaded Jinja2 environment
_jinja_env: Optional[Environment] = None


def _get_jinja_env() -> Environment:
    """Get or create the Jinja2 template environment."""
    global _jinja_env
    if _jinja_env is None:
        _jinja_env = Environment(
            loader=FileSystemLoader(str(_TEMPLATES_DIR)),
            autoescape=True,
        )
    return _jinja_env


def _risk_level(score: float) -> str:
    """Map a risk score to a CSS risk level class."""
    if score >= 75:
        return "critical"
    elif score >= 50:
        return "high"
    elif score >= 25:
        return "medium"
    return "low"


_DEFAULT_BRANDING = {
    "company_name": "Hydra Security",
    "logo_url": "",
    "analyst": "",
    "footer": "Generated by Hydra — LLM Security Assessment Platform",
    "primary_color": "#16213e",
}


def render_html(
    report: VulnerabilityReport,
    branding: Optional[dict] = None,
) -> str:
    """Render the vulnerability report as an HTML string.

    Parameters
    ----------
    report : VulnerabilityReport
        The report data to render.
    branding : dict, optional
        Tenant branding overrides. Missing keys fall back to defaults.

    Returns
    -------
    str
        Complete HTML document ready for display or PDF conversion.
    """
    env = _get_jinja_env()
    template = env.get_template("report.html")

    # Load CSS
    css_path = _TEMPLATES_DIR / "report.css"
    css = css_path.read_text() if css_path.exists() else ""

    # Merge branding with defaults
    effective_branding = {**_DEFAULT_BRANDING, **(branding or {})}

    return template.render(
        report=report,
        branding=effective_branding,
        css=css,
        risk_level=_risk_level(report.executive_summary.risk_score),
    )


def render_pdf(
    report: VulnerabilityReport,
    branding: Optional[dict] = None,
) -> bytes:
    """Render the vulnerability report as a PDF.

    Uses weasyprint when available. Falls back to UTF-8 HTML bytes
    if weasyprint is not installed (e.g. in test environments without
    system libraries).

    Parameters
    ----------
    report : VulnerabilityReport
        The report data to render.
    branding : dict, optional
        Tenant branding overrides.

    Returns
    -------
    bytes
        PDF document bytes (or HTML bytes if weasyprint unavailable).
    """
    html = render_html(report, branding)
    result = _html_to_pdf_or_fallback(html)
    logger.info("Generated report for scan %s (%d bytes)", report.scan_id, len(result))
    return result


def _html_to_pdf_or_fallback(html: str) -> bytes:
    """Convert HTML to PDF via weasyprint, falling back to raw HTML bytes."""
    try:
        from weasyprint import HTML as WeasyHTML
        return WeasyHTML(string=html).write_pdf()
    except ImportError:
        return html.encode("utf-8")
    except Exception as e:
        logger.warning("PDF generation failed, returning HTML: %s", e)
        return html.encode("utf-8")


def render_evidence_html(
    package: dict,
    branding: Optional[dict] = None,
) -> str:
    """Render a compliance evidence package as HTML."""
    env = _get_jinja_env()
    template = env.get_template("evidence_report.html")

    css_path = _TEMPLATES_DIR / "report.css"
    css = css_path.read_text() if css_path.exists() else ""

    return template.render(
        package=package,
        branding={**_DEFAULT_BRANDING, **(branding or {})},
        css=css,
    )


def render_evidence_pdf(
    package: dict,
    branding: Optional[dict] = None,
) -> bytes:
    """Render a compliance evidence package as PDF (or HTML fallback)."""
    html = render_evidence_html(package, branding)
    return _html_to_pdf_or_fallback(html)


def store_pdf_in_prism(
    pdf_bytes: bytes, scan_id: str, tenant_id: str,
) -> bool:
    """Store a PDF report in Prism.

    Key format: ``{tenant_id}/report:{scan_id}:pdf``
    """
    try:
        from services.object_store import get_object_store
        from services.report_generator import _set_tenant_if_supported

        store = get_object_store()
        _set_tenant_if_supported(store, tenant_id)

        key = f"{tenant_id}/report:{scan_id}:pdf"
        store.store(key, pdf_bytes)
        logger.info("Stored PDF report in Prism: %s (%d bytes)", key, len(pdf_bytes))
        return True
    except Exception as e:
        logger.warning("Failed to store PDF report: %s", e)
        return False
