"""
Celery task for executing garak scans.

Runs inside a Celery worker process — all I/O is synchronous (no asyncio).
The task communicates with the garak container over HTTP, consumes SSE
progress events, updates Postgres, and publishes progress to Redis Pub/Sub.
"""
import json
import logging
import time
from datetime import datetime
from typing import Any, Dict, Optional

import httpx

from tasks import celery_app, QUEUE_DEFAULT

logger = logging.getLogger(__name__)

# Redis Pub/Sub channel pattern for scan progress
PROGRESS_CHANNEL = "scan:{tenant_id}:{scan_id}:progress"


def _publish_progress(scan_id: str, tenant_id: str, event: dict) -> None:
    """Publish a progress event to Redis Pub/Sub.

    Uses native Redis PUBLISH for true pub/sub semantics.
    Non-critical — if Redis is unavailable, we log and continue.
    The WS/SSE endpoints will fall back to polling the DB.
    """
    try:
        import redis
        from config import settings
        channel = PROGRESS_CHANNEL.format(tenant_id=tenant_id, scan_id=scan_id)
        r = redis.from_url(settings.redis_url)
        r.publish(channel, json.dumps(event))
    except Exception as e:
        # Redis pub/sub is best-effort; DB is the source of truth
        logger.debug(f"Redis pub/sub publish failed (non-critical): {e}")


def _sync_scan_to_db(
    scan_id: str,
    tenant_id: str,
    status: str,
    config_dict: Optional[dict] = None,
    passed: int = 0,
    failed: int = 0,
    total_probes: int = 0,
    error_message: Optional[str] = None,
    started_at: Optional[str] = None,
    completed_at: Optional[str] = None,
    report_path: Optional[str] = None,
    html_report_path: Optional[str] = None,
    report_key: Optional[str] = None,
    html_report_key: Optional[str] = None,
) -> None:
    """Write scan state to the database (upsert).

    Delegates to the shared ``database.scan_ops.upsert_scan`` function
    so upsert logic is defined in exactly one place.
    """
    from database.scan_ops import upsert_scan

    config_json = json.dumps(config_dict) if config_dict else None
    target_type = config_dict.get("target_type", "unknown") if config_dict else "unknown"
    target_name = config_dict.get("target_name", "unknown") if config_dict else "unknown"

    upsert_scan(
        scan_id,
        tenant_id=tenant_id,
        status=status,
        target_type=target_type,
        target_name=target_name,
        passed=passed,
        failed=failed,
        total_probes=total_probes,
        error_message=error_message,
        started_at=started_at,
        completed_at=completed_at,
        report_path=report_path,
        html_report_path=html_report_path,
        report_key=report_key,
        html_report_key=html_report_key,
        config_json=config_json,
        created_at=started_at,
    )


@celery_app.task(
    name="tasks.execute_scan",
    bind=True,
    max_retries=2,
    default_retry_delay=60,
    acks_late=True,
)
def execute_scan(
    self,
    scan_id: str,
    config: dict,
    tenant_id: str = "default",
    garak_service_url: str = "http://garak:9090",
) -> Dict[str, Any]:
    """Execute a garak scan inside a Celery worker.

    This task:
    1. Posts the scan config to the garak service container.
    2. Consumes the SSE progress stream (synchronous).
    3. Writes status updates to Postgres with tenant_id.
    4. Publishes progress events to Redis Pub/Sub.

    Args:
        scan_id: Unique scan identifier (generated by the API layer).
        config: Scan configuration dict (serialized ScanConfigRequest).
        tenant_id: Tenant that owns this scan.
        garak_service_url: URL of the garak service.

    Returns:
        Final scan state dict.
    """
    started_at = datetime.now().isoformat()
    scan_state = {
        "scan_id": scan_id,
        "tenant_id": tenant_id,
        "status": "pending",
        "passed": 0,
        "failed": 0,
        "total_probes": 0,
        "progress": 0.0,
        "current_probe": None,
        "error_message": None,
        "started_at": started_at,
        "completed_at": None,
        "report_path": None,
        "html_report_path": None,
        "report_key": None,
        "html_report_key": None,
    }

    # Persist initial PENDING state
    _sync_scan_to_db(
        scan_id=scan_id,
        tenant_id=tenant_id,
        status="pending",
        config_dict=config,
        started_at=started_at,
        total_probes=len(config.get("probes") or []),
    )
    _publish_progress(scan_id, tenant_id, {
        "event_type": "status", "status": "pending", "scan_id": scan_id,
    })

    # --- Step 1: Send scan config to garak service ---
    try:
        with httpx.Client(base_url=garak_service_url, timeout=30.0) as client:
            response = client.post(
                "/scans",
                json={"scan_id": scan_id, "config": config},
            )
            response.raise_for_status()
    except (httpx.HTTPStatusError, Exception) as e:
        is_http_err = isinstance(e, httpx.HTTPStatusError)
        error_msg = (
            f"Garak service rejected scan: {e.response.status_code}"
            if is_http_err
            else f"Failed to reach garak service: {e}"
        )
        scan_state["status"] = "failed"
        scan_state["error_message"] = error_msg
        scan_state["completed_at"] = datetime.now().isoformat()
        _sync_scan_to_db(
            scan_id=scan_id, tenant_id=tenant_id, status="failed",
            error_message=error_msg, completed_at=scan_state["completed_at"],
            config_dict=config, started_at=started_at,
        )
        _publish_progress(scan_id, tenant_id, {
            "event_type": "error", "message": error_msg, "scan_id": scan_id,
        })
        try:
            raise self.retry(exc=e)
        except self.MaxRetriesExceededError:
            return scan_state

    # --- Step 2: Consume SSE progress stream ---
    scan_state["status"] = "running"
    _sync_scan_to_db(
        scan_id=scan_id, tenant_id=tenant_id, status="running",
        config_dict=config, started_at=started_at,
    )
    _publish_progress(scan_id, tenant_id, {
        "event_type": "status", "status": "running", "scan_id": scan_id,
    })

    # Small delay to let the garak service register the scan
    time.sleep(0.5)

    max_retries = 3
    for attempt in range(max_retries):
        try:
            with httpx.Client(
                base_url=garak_service_url,
                timeout=httpx.Timeout(connect=10.0, read=None, write=10.0, pool=10.0),
            ) as client:
                with client.stream("GET", f"/scans/{scan_id}/progress") as response:
                    if response.status_code != 200:
                        body = response.read()
                        logger.error(
                            f"SSE endpoint returned {response.status_code} for {scan_id}: {body.decode()}"
                        )
                        if attempt < max_retries - 1:
                            time.sleep(2 * (attempt + 1))
                            continue
                        scan_state["status"] = "failed"
                        scan_state["error_message"] = f"Garak service error: {response.status_code}"
                        scan_state["completed_at"] = datetime.now().isoformat()
                        _sync_scan_to_db(
                            scan_id=scan_id, tenant_id=tenant_id, status="failed",
                            error_message=scan_state["error_message"],
                            completed_at=scan_state["completed_at"],
                            config_dict=config, started_at=started_at,
                        )
                        return scan_state

                    for line in response.iter_lines():
                        if not line.startswith("data: "):
                            continue
                        try:
                            data = json.loads(line[6:])
                        except json.JSONDecodeError:
                            continue

                        _process_sse_event(scan_id, tenant_id, data, scan_state, config, started_at)

            # Stream ended normally
            if scan_state["status"] in ("running", "pending"):
                scan_state["status"] = "completed"
                scan_state["progress"] = 100.0
                scan_state["completed_at"] = datetime.now().isoformat()

            _sync_scan_to_db(
                scan_id=scan_id, tenant_id=tenant_id,
                status=scan_state["status"],
                passed=scan_state["passed"],
                failed=scan_state["failed"],
                total_probes=scan_state["total_probes"],
                completed_at=scan_state["completed_at"],
                report_path=scan_state.get("report_path"),
                html_report_path=scan_state.get("html_report_path"),
                report_key=scan_state.get("report_key"),
                html_report_key=scan_state.get("html_report_key"),
                config_dict=config, started_at=started_at,
            )
            _publish_progress(scan_id, tenant_id, {
                "event_type": "complete",
                "scan_id": scan_id,
                "passed": scan_state["passed"],
                "failed": scan_state["failed"],
            })
            return scan_state

        except Exception as e:
            logger.error(f"Error consuming progress stream for {scan_id} (attempt {attempt + 1}): {e}")
            if attempt < max_retries - 1:
                time.sleep(2 * (attempt + 1))
                continue

            scan_state["status"] = "failed"
            scan_state["error_message"] = f"Lost connection to garak service: {e}"
            scan_state["completed_at"] = datetime.now().isoformat()
            _sync_scan_to_db(
                scan_id=scan_id, tenant_id=tenant_id, status="failed",
                error_message=scan_state["error_message"],
                completed_at=scan_state["completed_at"],
                config_dict=config, started_at=started_at,
            )
            return scan_state

    return scan_state


def _process_sse_event(
    scan_id: str,
    tenant_id: str,
    event: dict,
    scan_state: dict,
    config: dict,
    started_at: str,
) -> None:
    """Process a single SSE event from the garak service.

    Updates scan_state in place, syncs to DB, and publishes to Redis.
    """
    etype = event.get("event_type")

    if etype == "status":
        scan_state["status"] = event.get("status", scan_state["status"])

    elif etype == "progress":
        scan_state["current_probe"] = event.get("probe")
        scan_state["progress"] = float(event.get("percent", scan_state["progress"]))
        scan_state["status"] = "running"

    elif etype == "probe_count":
        scan_state["total_probes"] = event.get("total", 0)

    elif etype == "result":
        scan_state["passed"] = event.get("total_passed", scan_state["passed"])
        scan_state["failed"] = event.get("total_failed", scan_state["failed"])

    elif etype == "report":
        rtype = event.get("report_type")
        path = event.get("path")
        if rtype == "html":
            scan_state["html_report_path"] = path
        elif rtype == "jsonl":
            scan_state["report_path"] = path
        # Sync report paths to DB immediately
        _sync_scan_to_db(
            scan_id=scan_id, tenant_id=tenant_id,
            status=scan_state["status"],
            passed=scan_state["passed"],
            failed=scan_state["failed"],
            report_path=scan_state.get("report_path"),
            html_report_path=scan_state.get("html_report_path"),
            config_dict=config, started_at=started_at,
        )

    elif etype == "complete":
        scan_state["status"] = "completed"
        scan_state["progress"] = 100.0
        scan_state["completed_at"] = datetime.now().isoformat()
        scan_state["passed"] = event.get("passed", scan_state["passed"])
        scan_state["failed"] = event.get("failed", scan_state["failed"])
        report_keys = event.get("report_keys", {})
        if report_keys.get("jsonl"):
            scan_state["report_key"] = report_keys["jsonl"]
        if report_keys.get("html"):
            scan_state["html_report_key"] = report_keys["html"]

    elif etype == "error":
        scan_state["status"] = "failed"
        scan_state["error_message"] = event.get("message")
        scan_state["completed_at"] = datetime.now().isoformat()

    # Publish every event to Redis Pub/Sub
    _publish_progress(scan_id, tenant_id, {
        **event,
        "scan_id": scan_id,
    })
